# Generated by Django 4.0.2 on 2022-02-26 06:37

import Teridix_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teridix_account', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True),
        ),
    ]
