# Generated by Django 3.2.4 on 2022-02-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teridix_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
