# Generated by Django 4.0.2 on 2022-02-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teridix_main', '0003_contactusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت خواندن'),
        ),
    ]
